### ISSUE TITLE
Black squares in Gmail

### ISSUE THREAD

**Issue by inkubux** [manusa/electronim#106]
When using Gmail in Electronim there is a bunch of black/grey squares instead of icons

![image](https://user-images.githubusercontent.com/342110/189981719-e5895140-9182-4dd0-9b8c-10229159ca4e.png)
 
I played a little bit with the code and found it was the `google account` user agent rules that caused the issue. 

It causes gmail to fetch css rules targetted at firefox.

in `src/user-agent/index.js` 

```
 if (
          details.url.match(/https?:\/\/[^/]+google\.com.*/) && // NOSONAR
          !details.url.match(/https?:\/\/meet.google\.com.*/)
        ) {
```

If you replace it 
```
if (details.url.match(/https?:\/\/accounts.google\.com.*/)) {
```

It fix the issue and all google sign-in I could test still worked

I didn't create a pull-request only because I did not know if you had this rule for other things google related

Thanks for your great app.

**Comment by manusa** [comment]
Hi @inkbux

Thx for reporting. That's something really odd.

AFAIR this might have been added to allow webcam usage in Google Meet (#46).

We need to check if by providing better scope for the intercept we can make both things work. Maybe it's not even necessary anymore.

Please, feel free to create a PR if you feel comfortable providing a fix that fits both use-cases (GMail + GMeet). It's great for the project to get involvement from the community.

**Comment by inkubux** [comment]
I created a small PR
https://github.com/manusa/electronim/pull/110

Finally just adding `!details.url.match(/https?:\/\/meet.google\.com.*/)` was enough. 

Using `details.url.match(/https?:\/\/accounts.google\.com.*/)` would make the sign-in fail and give a "browser" security check from google

Hope it helps :)

**Comment by manusa** [comment]
> Hope it helps :)

That's awesome, thx!

**Comment by manusa** [comment]
> Finally just adding !details.url.match(/https?:\/\/meet.google\.com.*/) was enough. (sic)

I think you meant here `mail.google.com`.


Yes, sorry I mislead you with [my comment](https://github.com/manusa/electronim/issues/106#issuecomment-1246710435). After checking better the code, the interceptor was added [to allow logging in to Google services](https://github.com/manusa/electronim/commit/a05b092ba2f1a41d9386f5712c9102d255f75c56).
I can't remember why I originally implemented it this way, neither can't find an issue or any documentation for this. _(that's why you always need to create issues, document, implement test, and so on. Your future self will be grateful :sweat_smile: )_
