### ISSUE TITLE
Can not login to zoho mail

### ISSUE THREAD

**Issue by tkontogi** [manusa/electronim#248]
Hi,

Trying to login to zoho mail (mail.zoho.com) opens a main browser window, outside ElectronIM.

Happy to help you to help us.

Cheers,
Theo

**Comment by manusa** [comment]
This is caused because Zoho uses a SSO page located at a different origin.

We've maintain a list of exceptions here:
https://github.com/manusa/electronim/blob/22e4fdd48807ab44f53e33097f3fc62ca1eaa7bb/src/tab-manager/redirect.js#L21-L40

Could you please confirm what's the URL opened in the external browser window.
I found
- https://accounts.zoho.com/signin
- https://accounts.zoho.eu/signin

as options. But just to be sure we fix your issue.

We should also find a more sustainable solution like the one proposed at https://github.com/manusa/electronim/issues/42#issuecomment-759357375

**Comment by tkontogi** [comment]
Hi,

Thank you for following up.

The provided URLs are valid but are used for generic login to all zoho services.
All zoho URLs are geo-linked, one for EU and one for the rest of world.

For specific e-mail login, the redirection points directly to: 

-  [https://accounts.zoho.com/signin?servicename&serviceurl=https://mail.zoho.eu]

(or zoho.eu for EU based accounts).

Happy to provide more info as requested.
